"""
listed_analysis.py
Week 1 - Monthly Dataset Aggregation (Listed Transactions)

This script concatenates all monthly CRMLSListing CSV files from January 2024
through March 2026 into a single combined dataset, filters for Residential
properties only, and saves the result as a clean CSV.

Author: Ruoyu Wang
Date: April 2026
"""

import pandas as pd
import os
import glob

# ============================================================
# CONFIGURATION - Update these paths to match your local setup
# ============================================================

# Directory where the FTP-downloaded raw CSV files are stored (Jan 2024 - Jan 2026)
RAW_DATA_DIR = r"D:\IDXexchange\raw"

# Directory where the script-generated CSV files are stored (Feb 2026, Mar 2026)
GENERATED_DATA_DIR = r"D:\IDXexchange\week1"

# Output file path
OUTPUT_DIR = r"D:\IDXexchange\week1"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "combined_listed.csv")

# ============================================================
# STEP 1: Load all monthly Listing CSV files
# ============================================================

print("=" * 60)
print("STEP 1: Loading all monthly Listing CSV files")
print("=" * 60)

# Build list of all listing CSV file paths
listing_files = []

# Monthly files from Jan 2024 to Jan 2026 (from FTP raw folder)
for year in [2024, 2025, 2026]:
    if year == 2024:
        months = range(1, 13)  # Jan - Dec 2024
    elif year == 2025:
        months = range(1, 13)  # Jan - Dec 2025
    elif year == 2026:
        months = range(1, 2)   # Jan 2026 only (from FTP)
    
    for month in months:
        filename = f"CRMLSListing{year}{month:02d}.csv"
        filepath = os.path.join(RAW_DATA_DIR, filename)
        if os.path.exists(filepath):
            listing_files.append(filepath)
        else:
            print(f"  [WARNING] File not found: {filepath}")

# Feb 2026 and Mar 2026 (generated by crmls_listed.py)
for month in [2, 3]:
    filename = f"CRMLSListing2026{month:02d}.csv"
    filepath = os.path.join(GENERATED_DATA_DIR, filename)
    if os.path.exists(filepath):
        listing_files.append(filepath)
    else:
        print(f"  [WARNING] File not found: {filepath}")

print(f"\nTotal files found: {len(listing_files)}")
for f in listing_files:
    print(f"  - {os.path.basename(f)}")

# ============================================================
# STEP 2: Read and concatenate all files
# ============================================================

print("\n" + "=" * 60)
print("STEP 2: Reading and concatenating all files")
print("=" * 60)

dfs = []
for filepath in listing_files:
    df = pd.read_csv(filepath, low_memory=False)
    print(f"  {os.path.basename(filepath)}: {len(df)} rows, {len(df.columns)} columns")
    dfs.append(df)

# Concatenate all dataframes
listings = pd.concat(dfs, ignore_index=True)

print(f"\n>>> Total rows after concatenation: {len(listings)}")
print(f">>> Total columns: {len(listings.columns)}")

# ============================================================
# STEP 3: Inspect PropertyType distribution
# ============================================================

print("\n" + "=" * 60)
print("STEP 3: PropertyType distribution (before filtering)")
print("=" * 60)

print("\nUnique PropertyType values:")
print(listings['PropertyType'].value_counts())

print(f"\nTotal rows before Residential filter: {len(listings)}")

# ============================================================
# STEP 4: Filter for Residential properties only
# ============================================================

print("\n" + "=" * 60)
print("STEP 4: Filtering for PropertyType == 'Residential'")
print("=" * 60)

listings = listings[listings['PropertyType'] == 'Residential'].copy()

print(f">>> Total rows after Residential filter: {len(listings)}")

# ============================================================
# STEP 5: Basic data overview
# ============================================================

print("\n" + "=" * 60)
print("STEP 5: Basic data overview")
print("=" * 60)

print(f"\nShape: {listings.shape}")
print(f"\nColumn data types:\n{listings.dtypes}")
print(f"\nFirst 5 rows:")
print(listings.head())

# ============================================================
# STEP 6: Save combined dataset
# ============================================================

print("\n" + "=" * 60)
print("STEP 6: Saving combined Residential listing dataset")
print("=" * 60)

listings.to_csv(OUTPUT_FILE, index=False)
print(f">>> Saved to: {OUTPUT_FILE}")
print(f">>> Final row count: {len(listings)}")
print(f">>> Final column count: {len(listings.columns)}")

print("\n" + "=" * 60)
print("DONE - Listing dataset aggregation complete")
print("=" * 60)
